<?php

/*
 * Implement hook_views_api()
 */
function flag_hidden_views_api() {
  return array('api' => 2.0);
}

/*
 * Implement hook_flag_default_flags()
 */
function flag_hidden_flag_default_flags() {
  $flags = array();
  // Exported flag: "Hidden Node".
  $flags['hidden_node'] = array(
    'content_type' => 'node',
    'title' => 'Hidden Node',
    'global' => '1',
    'types' => array(),
    'flag_short' => 'Hide [node:type-name]',
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => 'Unhide [node:type-name]',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'normal',
    'roles' => array(),
    'show_on_page' => 0,
    'show_on_teaser' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'api_version' => 2,
  );
  return $flags;
}

/*
 * Add robots META tags for hidden nodes and our hidden view.
 */

/*
 * Implement hook_page_alter
 */
function flag_hidden_page_alter() {
  if(flag_hidden_page_is_hidden_node() ||
     flag_hidden_page_is_hidden_view()) {
    flag_hidden_add_robots_meta_tag();
  }
}

function flag_hidden_add_robots_meta_tag() {
  $element = array(
    '#tag' => 'meta',
    '#attributes' => array(
      'name' => 'robots',
      'content' => 'noindex, nofollow',
    ),
  );
  drupal_add_html_head($element, 'robots-noindex');
}

function flag_hidden_page_is_hidden_node() {
  $current_node = menu_get_object('node');
  if($current_node) {
    $flag = flag_get_flag('hidden_node');
    return ($flag && $flag->is_flagged($current_node->nid));
  }

  return FALSE;
}


function flag_hidden_page_is_hidden_view() {
  $page_view = views_get_page_view();

  return ($page_view && $page_view->name == 'hidden_nodes');
}

